### ISSUE TITLE
SEVERE: Error while loading vpk file: Invalid signature

### ISSUE THREAD

**Issue by Tooop22** [Dylancyclone/VMF2OBJ#45] opened 2023-04-29 10:56 UTC
I get this error when trying to convert
![Capture](https://user-images.githubusercontent.com/128878655/235298972-bb65d4dc-e470-4985-99ff-e29cbf5b4d18.PNG)

**Comment by DoritoTheChips** [comment] 2023-05-06 16:58
Do not use the `garrysmod_xxx.vpk` files, only use the `garrysmod_dir.vpk` files.

**Comment by Dylancyclone** [comment] 2024-01-14 00:01
Hi I'm going to close this since I'm guessing the issue is resolved. Feel free to respond or create a new issue if you're still having trouble.

**Closed by Dylancyclone** 2024-01-14 00:01 UTC
