### ISSUE TITLE
Got an error after reading geometry.

### ISSUE THREAD

**Issue by JerzynDev** [Dylancyclone/VMF2OBJ#18] opened 2021-06-20 16:31 UTC
Starting VMF2OBJ conversion v1.1.3
[1/5] Reading VPK file(s)...
[2/5] Reading geometry...
Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 2641 path $.solids[0].sides[0].null
        at com.google.gson.Gson.fromJson(Gson.java:942)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at com.lathrum.VMF2OBJ.dataStructure.map.VMF.parseVMF(VMF.java:243)
        at com.lathrum.VMF2OBJ.App.main(App.java:510)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1 column 2641 path $.solids[0].sides[0].null
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:491)
        at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        ... 5 more

**Comment by Dylancyclone** [comment] 2021-06-27 00:57
Hi!
What map are you trying to convert?

**Comment by Meowming** [comment] 2022-03-19 10:11
I had the same errors while converting Black Mesa's vmf files. Mine was bm_c1a0a.vmf

**Comment by Meowming** [comment] 2022-03-19 10:14
My log:
>> java -jar .\VMF2OBJ-1.1.3.jar .\input.vmf .\output "E:\Program Files (x86)\Steam\steamapps\common\Black Mesa\bms\bms_textures_dir.vpk"
Starting VMF2OBJ conversion v1.1.3
[1/5] Reading VPK file(s)...
[2/5] Reading geometry...
Exception in thread "main" com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 6764560 path $.entities[3147].connections.
        at com.google.gson.Gson.fromJson(Gson.java:942)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at com.lathrum.VMF2OBJ.dataStructure.map.VMF.parseVMF(VMF.java:243)
        at com.lathrum.VMF2OBJ.App.main(App.java:510)
Caused by: com.google.gson.stream.MalformedJsonException: Expected ':' at line 1 column 6764560 path $.entities[3147].connections.
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:530)
        at com.google.gson.stream.JsonReader.skipValue(JsonReader.java:1232)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        ... 5 more
PS E:\Program Files (x86)\Steam\steamapps\common\Black Mesa>

**Comment by Dylancyclone** [comment] 2022-05-24 21:53
Hello! I believe this has been fixed in version 2.0.0, or at least I was not able to reproduce it in the new version. If you are still having problems please feel free to reopen!

**Closed by Dylancyclone** 2022-05-24 21:53 UTC
Labels: info needed
